name: flame_101_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.28.0
  provider: ^6.1.4
  audioplayers: ^6.4.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:    
    - assets/images/
    - assets/audio/

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/myFont.ttf